import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'firebase_options.dart'; // generated by: flutterfire configure
import 'theme/app_theme.dart';
import 'core/providers/theme_service_provider.dart';

import 'features/auth/presentation/screens/onboarding_screen.dart';
import 'features/auth/presentation/screens/login_screen.dart';
import 'features/auth/presentation/screens/signup_screen.dart';
import 'features/auth/presentation/screens/fill_profile_screen.dart';
import 'features/onboarding/presentation/screens/select_country_screen.dart';
import 'features/onboarding/presentation/screens/choose_topics_screen.dart';
import 'features/onboarding/presentation/screens/choose_news_sources_screen.dart';
import 'features/home/presentation/screens/main_app_scaffold.dart';
import 'features/home/presentation/screens/trending_screen.dart';
import 'features/home/presentation/screens/notifications_screen.dart';
import 'features/profile/presentation/screens/create_post_screen.dart';
import 'features/profile/presentation/screens/edit_profile_screen.dart';
import 'features/profile/presentation/screens/settings_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase before anything else
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize Google Sign-In singleton (Required in v7.0.0+).
  // On Web, the clientId is read from the <meta name="google-signin-client_id"> tag
  // in web/index.html — see README for setup. Skip on web until that is configured.
  if (!kIsWeb) {
    await GoogleSignIn.instance.initialize();
  }

  final prefs = await SharedPreferences.getInstance();
  final bool isFirstRun = prefs.getBool('isFirstRun') ?? true;

  runApp(ProviderScope(child: MyApp(isFirstRun: isFirstRun)));
}

class MyApp extends ConsumerWidget {
  final bool isFirstRun;
  const MyApp({super.key, required this.isFirstRun});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeServiceProvider);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'News App',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
      initialRoute: isFirstRun ? '/onboarding' : '/login',
      routes: {
        '/onboarding': (context) => const OnboardingScreen(),
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/topics': (context) => const ChooseTopicsScreen(),
        '/news-sources': (context) => const ChooseNewsSourcesScreen(),
        '/fill-profile': (context) => const FillProfileScreen(),
        '/select-country': (context) => const SelectCountryScreen(),
        '/home': (context) => const MainAppScaffold(initialIndex: 0),
        '/explore': (context) => const MainAppScaffold(initialIndex: 1),
        '/trending': (context) => const TrendingScreen(),
        '/notifications': (context) => const NotificationsScreen(),
        '/settings': (context) => const SettingsScreen(),
        '/create-post': (context) => const CreatePostScreen(),
        '/edit-profile': (context) => const EditProfileScreen(),
      },
    );
  }
}
